projects:
  Dresser-staging:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: udag3z736jhqrls3qkd66dnkdy
        maxDepth: 2
extensions:
  amplify:
    version: 3
